name: Run scanner

on:
  push:
    branches: [ "master" ]
  repository_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: thepbone/app-crawler

    - uses: actions/checkout@v3
      with:
        repository: thepbone/awesome-shizuku
        path: './list'
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run crawler
      env: 
        GITHUB_AUTH: ${{ secrets.GH_PAT }}
      run: |
        python main.py ./list
        cat SUMMARY.md >> $GITHUB_STEP_SUMMARY

    - name: Commit summary
      env: 
        CI_COMMIT_MESSAGE: Update SUMMARY.md
        CI_COMMIT_AUTHOR: thepbone
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "38386967+ThePBone@users.noreply.github.com"
        git add SUMMARY.md
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
    
        
