name: Run scanner

on:
  push:
    branches: [ "master" ]
  repository_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: thepbone/app-crawler

    - uses: actions/checkout@v3
      with:
        repository: thepbone/awesome-shizuku
        path: './list'
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run crawler
      env: 
        GITHUB_AUTH: ${{ secrets.GH_PAT }}
      run: |
        python main.py ./list
        cat SUMMARY.md >> $GITHUB_STEP_SUMMARY

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'SUMMARY.md'
       
        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actor
    
        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Update SUMMARY.md'

        
